name: 1.0.$(Date:yyyyMMdd)$(Rev:.rr)

trigger:
  branches:
    include:
      - dev

pr:
  branches:
    include:
      - dev

variables:
  - group: var-group-finaipro-azf-dev

pool: Azure Pipelines

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build Job'
    steps:
    - script: |
        echo "Building the project..."
        mkdir -p $(Build.ArtifactStagingDirectory)
        cp -R * $(Build.ArtifactStagingDirectory)/
      displayName: 'Run build script'
    
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'AzureFunctionArtifact'
        publishLocation: 'Pipeline'

- stage: Test
  displayName: 'Test Stage'
  jobs:
  - job: Test
    displayName: 'Test Job'
    steps:
    - script: |
        echo "Running tests..."
        dotnet test --configuration Release --no-build
      displayName: 'Run unit tests'

- stage: Deploy
  displayName: 'Deploy Stage'
  jobs:
  - job: Deploy
    displayName: 'Deploy Job'
    steps:
    - download: current
      artifact: 'AzureFunctionArtifact'
    
    - task: AzureFunctionApp@1
      displayName: 'Deploy to Azure Function App'
      inputs:
        azureSubscription: $(AZURE_SERVICE_CONNECTION)
        appType: functionAppLinux
        appName: 'azf-finaipro-dev2-eu02'
        package: '$(Pipeline.Workspace)/AzureFunctionArtifact'