name: 1.0.$(Date:yyyyMMdd)$(Rev:.rr)

trigger:
  branches:
    include:
      - dev

pr:
  branches:
    include:
      - dev

variables:
  AZURE_SERVICE_CONNECTION: 'FinAIPro_Desarrollo (7107c132-512a-4a4c-bbfd-9faacc45ad09)'
  AZ_SUBSCRIPTION_NAME: 'FinAIPro_Desarrollo (7107c132-512a-4a4c-bbfd-9faacc45ad09)'
  AZF_NAME: 'azf-finaipro-dev2-eu02'  

pool: 
  vmImage: 'windows-latest'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build Job'
    steps:
    - script: |
        echo "Building the project..."
        mkdir -p $(Build.ArtifactStagingDirectory)/drop
        cp -R * $(Build.ArtifactStagingDirectory)/drop/
      displayName: 'Run build script'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/drop'
        artifact: 'AZF_Artifact'
        publishLocation: 'Pipeline'

- stage: Deploy
  dependsOn:
    - Build
  displayName: 'Deploy Stage'
  jobs:
  - job: DeployAzureFunctions
    displayName: 'Deploy Azure Functions'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifactName: 'AZF_Artifact'
        downloadPath: '$(Pipeline.Workspace)/AZF_Artifact'

    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: '$(AZURE_SERVICE_CONNECTION)'
        appType: 'functionApp'
        appName: '$(AZF_NAME)'
        package: '$(Pipeline.Workspace)/AZF_Artifact/drop'
