name: 1.0.$(Date:yyyyMMdd)$(Rev:.rr)

trigger:
  - dev

pr:
  - dev

variables:
  - group: var-group-finaipro-azf-dev

pool:
  Azure Pipelines

stages:
  - stage: Build
    displayName: 'Etapa de compilaci贸n'
    jobs:
      - job: Build
        displayName: 'Trabajo de compilaci贸n'
        steps:
          - script: |
              echo "Compilando el proyecto..."
              mkdir -p $(Build.ArtifactStagingDirectory)
              cp -R * $(Build.ArtifactStagingDirectory)/
            displayName: 'Ejecutar script de compilaci贸n'

          - script: |
              echo "Copiando variables de entorno..."
              chmod +x copy_env_variables.sh
              ./copy_env_variables.sh
            displayName: 'Copiar variables de entorno'

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)'
              artifact: 'AZF Artifact'
              publishLocation: 'Pipeline'

  - stage: Deploy
    dependsOn:
      - Build
    displayName: 'Etapa de implementaci贸n'
    jobs:
      - job: DeployAzureFunctions
        displayName: 'Implementar funciones de Azure'
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: 'AZF Artifact'
              downloadPath: '$(Pipeline.Workspace)/AZF Artifact'

          - script: |
              echo "APPINSIGHTS_INSTRUMENTATIONKEY=$(appSetting_APPINSIGHTS_INSTRUMENTATIONKEY)"
              echo "AzureWebJobsFeatureFlags=$(appSetting_AzureWebJobsFeatureFlags)"
              echo "DATALAKE_ACCESS_KEY=$(appSetting_DATALAKE_ACCESS_KEY)"
              echo "DATALAKE_ACCOUNT_NAME=$(appSetting_DATALAKE_ACCOUNT_NAME)"
              echo "DATALAKE_CONTAINER_NAME=$(appSetting_DATALAKE_CONTAINER_NAME)"
              echo "DATALAKE_TARGET_BASE_FOLDER=$(appSetting_DATALAKE_TARGET_BASE_FOLDER)"
              echo "DATALAKE_TARGET_CONTAINER_NAME=$(appSetting_DATALAKE_TARGET_CONTAINER_NAME)"
              echo "KEYVAULT_URL=$(appSetting_KEYVAULT_URL)"
              echo "TRADING_ECONOMICS_INDICATORS=$(appSetting_TRADING_ECONOMICS_INDICATORS)"
            displayName: 'Mostrar variables de entorno'

          - task: AzureFunctionApp@1
            inputs:
              azureSubscription: '$(AZURE_SERVICE_CONNECTION)'
              appType: 'functionApp'
              appName: '$(AZF_NAME)'
              package: '$(Pipeline.Workspace)/AZF Artifact'
              runtimeStack: 'DOTNET|6.0'
              appSettings: |
                - name: APPINSIGHTS_INSTRUMENTATIONKEY
                  value: $(appSetting_APPINSIGHTS_INSTRUMENTATIONKEY)
                  slotSetting: false
                - name: AzureWebJobsFeatureFlags
                  value: $(appSetting_AzureWebJobsFeatureFlags)
                  slotSetting: false
                - name: DATALAKE_ACCESS_KEY
                  value: $(appSetting_DATALAKE_ACCESS_KEY)
                  slotSetting: false
                - name: DATALAKE_ACCOUNT_NAME
                  value: $(appSetting_DATALAKE_ACCOUNT_NAME)
                  slotSetting: false
                - name: DATALAKE_CONTAINER_NAME
                  value: $(appSetting_DATALAKE_CONTAINER_NAME)
                  slotSetting: false
                - name: DATALAKE_TARGET_BASE_FOLDER
                  value: $(appSetting_DATALAKE_TARGET_BASE_FOLDER)
                  slotSetting: false
                - name: DATALAKE_TARGET_CONTAINER_NAME
                  value: $(appSetting_DATALAKE_TARGET_CONTAINER_NAME)
                  slotSetting: false
                - name: KEYVAULT_URL
                  value: $(appSetting_KEYVAULT_URL)
                  slotSetting: false
                - name: TRADING_ECONOMICS_INDICATORS
                  value: $(appSetting_TRADING_ECONOMICS_INDICATORS)
                  slotSetting: false
